Fix test_timing flakiness under Windows:
Observed:

```
> assert delay_ms <= elapsed_time_ms < delay_ms + generous_tolerance
E assert 500.0 <= 490.03173828125
test_event.py:41: AssertionError
```

The generous_tolerance also needs to be applied when checking the lower bound.